[package]
name = "nip-19-decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr = "0.38.0"
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"
